### ISSUE TITLE
BUG: Display of NIT's and other colleges

### ISSUE THREAD

**Issue by jaswanthsanapala** [AYushM25/College-Pathfinder_1#11]
In the home page, when we click on NIT’s/Other colleges it is redirecting to the “Search” page but there were only IIT’s in that section.

**Expected Behavior**
I should get the list of NIT's and other colleges

**Comment by Anitejjain** [comment]
Due to less time we were unable to include NIT's and other exams in our site. Currently our whole site is based on JEE Advanced Examination We can extend it further in College Search section that's why we have provided link of college Search in NIT's currently.
