### ISSUE TITLE
BUG: Reporting in Forum

### ISSUE THREAD

**Issue by jaswanthsanapala** [AYushM25/College-Pathfinder_1#12]
Once a user reports a particular review in forum then if we report it again it is removing my report option and most importantly there is no functionality taken for the report option in the backend (like deleting the post or having a conversation with the reviewer etc…)

**Remarks**
Can be insecure because any random person can report a good review

**Comment by Anitejjain** [comment]
There is functionality for admin by which he can delete post. Admin can look if there are reports and if find them justified he can delete post.

**Comment by jaswanthsanapala** [comment]
Comment in github

**Comment by jaswanthsanapala** [comment]
The thing is that there is no such function which takes that report. You
people have just added that report button and there is no functionality or
the person who is reporting it

**Comment by SmartCheese22** [comment]
The reports on user posts are visible even to the admin. As for the function, the backend has the function handling the reports implemented. The admin has the functionality to delete the post accordingly. If you still think there is an issue, please let me know.
