### ISSUE TITLE
BUG: Follow Us on Home Page

### ISSUE THREAD

**Issue by jaswanthsanapala** [AYushM25/College-Pathfinder_1#15]
The ‘Follow us' links on Homepage are mentioned but they don't redirect to the required page and mainly they aren't working.

**Comment by Anitejjain** [comment]
There are not pages on Instagram, Facebook etc of College PathFinder that's why we have not added them currently . But we surely plan it to do further.

**Comment by jaswanthsanapala** [comment]
Don't close any bugs. Just inform us then we will check it and then if the
bug is resolved then close it
